### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by leifmerget**
Hello I really like this library. I have made a curtian with aproximatly 3000 leds and want to control it via resolume/artnet/ethernet. When uploading the example code to an esp32 an guru error. do you have advice on how to fix this? Thanks

The error
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d1412  PS      : 0x00060a30  A0      : 0x800d1674  A1      : 0x3ffb27a0  
A2      : 0x3ffc10d8  A3      : 0x3ffbdb6c  A4      : 0x00000001  A5      : 0x3ffc14d8  
A6      : 0x00000124  A7      : 0x3ffc11d8  A8      : 0xc0100000  A9      : 0x00000000  
A10     : 0x00013ffc  A11     : 0x00000094  A12     : 0x0ffd114c  A13     : 0x00000000  
A14     : 0x00060a20  A15     : 0x00000001  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400d194c  LEND    : 0x400d1954  LCOUNT  : 0x00000000  

Backtrace:0x400d140f:0x3ffb27a00x400d1671:0x3ffb27c0 0x400d1960:0x3ffb27f0 0x400d287e:0x3ffb2820 

ELF file SHA256: 0000000000000000

Rebooting...

### CODE REVIEW

**Comment by hpwit** [comment]
hello which example did you try ?
you need to upload the  dev version of the I2SClocklessLeddriver also
I am currently doing a lot of changes in the dev version  of the Artnet lib so maybe that is what .

**Comment by hpwit** [comment]
could you please retry the new dev branch and also the dev branch of I2SClocklessLeddriverplease

**Comment by leifmerget** [comment]
Thank you will try this.

**Comment by leifmerget** [comment]
Thanks. The problem we had was that we had declared a different number in NUMSTRIPS than the number in our array of pins. Although we fixed that, we are getting a different error when trying to implement ethernet. Do you have any exmaple code/advice on how to do that?
Here's the error:
`ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4

assert failed: tcpip_api_call IDF/components/lwip/lwip/src/api/tcpip.c:497 (Invalid mbox)


Backtrace:0x4008374d:0x3ffb25800x40088079:0x3ffb25a0 0x4008cdcd:0x3ffb25c0 0x400dd09e:0x3ffb26f0 0x400d270a:0x3ffb2720 0x400d272c:0x3ffb27c0 0x400d1ba8:0x3ffb27e0 0x400d3a6a:0x3ffb2820 




ELF file SHA256: 0000000000000000
`

Thanks again.

By the way, here's a picture of our curtian:
https://drive.google.com/file/d/1_QJteKJsVStgAYwQirk4k3rS8Pm9tInY/view?usp=sharing

**Comment by hpwit** [comment]
Hello
Can I see the code please. Which version of the esp core are you using ? 
rgds
Yves.  Ps we should switch that discussion to issues and not pull requests ;)

**Comment by leifmerget** [comment]
Here is the code. I am using the DOIT ESP32 DEVKITV1 core on platformio. 

#define NUM_LEDS_PER_STRIP 100
#define NUMSTRIPS 2
#define NB_CHANNEL_PER_LED 3 //Should be 4 if your sending tool is sending RGBW
#define COLOR_GRB
#define UNIVERSE_SIZE_IN_CHANNEL  (170 * 3)  //here we define a universe of 170 pixels each pixel is composed of 3 channels
#define START_UNIVERSE 0
//#define USE_PIXELSLIB
#include <Ethernet.h>
#include "I2SClocklessLedDriver.h"
#include "Arduino.h"
#include "WiFi.h"
#include "artnetESP32V2.h"
//here we have 3 colors per pixel

// int pins[16]={2,4,5,12,13,14,15,17,16,19,21,22,23,25,26};
int pins[2]={2,4};

const IPAddress ip(10, 101, 100, 13);
uint8_t mac[] = {0x01, 0x23, 0x45, 0x67, 0x89, 0xAB};

artnetESP32V2 artnet=artnetESP32V2();
I2SClocklessLedDriver driver;
  void displayfunction(uint8_t * data){

     driver.showPixels(NO_WAIT,data);
}

void setup() {
  // put your setup code here, to run once:
Serial.begin(115200);
    /* if you do not use the driver for other thing than artnet you do not
     * need to put a led buffer. If you need one you can use it. In this example It's not needed
     * as the subArtnet contains the buffer to be displayed.
     */
   driver.initled(NULL,pins,NUMSTRIPS,NUM_LEDS_PER_STRIP);  
    driver.setBrightness(20);
    Ethernet.init(5);
    Ethernet.begin(mac, ip);
    /* We add the subartnet reciever. Here we only need one
     * addSubartnet (Start universe,size of data,number of channel per universe,callback function)
     * NUM_LEDS_PER_STRIP * NUMSTRIPS is the total number of leds 
     * NUM_LEDS_PER_STRIP * NUMSTRIPS * NB_CHANNEL_PER_LED is the total number of channels needed here 3 channel per led (R,G,B)
     */ 
    artnet.addSubArtnet(START_UNIVERSE ,NUM_LEDS_PER_STRIP * NUMSTRIPS * NB_CHANNEL_PER_LED,UNIVERSE_SIZE_IN_CHANNEL ,&displayfunction);
    
    if(artnet.listen(6454)) {
        Serial.print("artnet Listening on IP: ");
    }
}

void loop()
{
  vTaskDelete(NULL);
}

**Comment by hpwit** [comment]
could you decode the backtrace error code ?

**Pull request merged**
